using System;
using UnityEngine;
using JasmineYamo.ComponentAutoBind;
using UnityEngine.UI;

namespace JasmineYamo.ComponentAutoBind.Samples.BasicUGUI
{
    // Generated by Component Auto Bind. Do not edit manually.
    public partial class BasicAutoBindTarget : IAutoBindHost
    {
        [Serializable]
        public class UIView : IUiViewComponent
        {
            public Button submitButton;
            public Text statusText;
        }

        private UIView view;

        [global::System.CodeDom.Compiler.GeneratedCode("Component Auto Bind", "0.2.0")]
        public void EnsureAutoBind(GameObject go)
        {
            if (view != null)
            {
                return;
            }

            if (go == null)
            {
                Debug.LogError("[BasicAutoBindTarget] Auto Bind failed: target GameObject is null.");
                return;
            }

            ComponentAutoBindTool autoBindTool = go.GetComponent<ComponentAutoBindTool>();
            if (autoBindTool == null)
            {
                Debug.LogError("[BasicAutoBindTarget] Auto Bind failed: ComponentAutoBindTool was not found.", go);
                return;
            }

            view = new UIView
            {
                submitButton = autoBindTool.GetBindComponent<Button>(0, nameof(UIView.submitButton)),
                statusText = autoBindTool.GetBindComponent<Text>(1, nameof(UIView.statusText))
            };
        }
    }
}
