using System;
using UnityEngine;
using JasmineYamo.ComponentAutoBind;
using UnityEngine.UI;

namespace JasmineYamo.ComponentAutoBind.Samples.BasicUGUI
{
    // Generated by Component Auto Bind. Do not edit manually.
    public partial class BasicAutoBindTarget : IAutoBindTarget
    {
        [Serializable]
        public sealed class AutoBindComponentSet : IAutoBindComponentSet
        {
            public Button submitButton;
            public Text statusText;
        }

        private AutoBindComponentSet m_AutoBindComponents;

        public void EnsureAutoBind(GameObject go)
        {
            if (m_AutoBindComponents != null)
            {
                return;
            }

            if (go == null)
            {
                Debug.LogError("[BasicAutoBindTarget] Auto Bind failed: target GameObject is null.");
                return;
            }

            ComponentAutoBindTool autoBindTool = go.GetComponent<ComponentAutoBindTool>();
            if (autoBindTool == null)
            {
                Debug.LogError("[BasicAutoBindTarget] Auto Bind failed: ComponentAutoBindTool was not found.", go);
                return;
            }

            m_AutoBindComponents = new AutoBindComponentSet
            {
                submitButton = autoBindTool.GetBindComponent<Button>(0, nameof(AutoBindComponentSet.submitButton)),
                statusText = autoBindTool.GetBindComponent<Text>(1, nameof(AutoBindComponentSet.statusText))
            };
        }
    }
}
