using System;
using JasmineYamo.ComponentAutoBind;
using UnityEngine;
using UnityEngine.UI;

namespace JasmineYamo.SimpleUI.VContainer.Samples.ResourcesDemo.Demo
{
    // Generated by Component Auto Bind. Do not edit manually.
    public partial class HomeView : IAutoBindHost
    {
        [Serializable]
        public new class UIView : IUiViewComponent
        {
            public Text statusText;
            public Button showDetailButton;
            public Button queueDetailButton;
            public Button replaceDetailButton;
            public Button closeButton;
        }

        private new UIView view;

        [global::System.CodeDom.Compiler.GeneratedCode(
            "Component Auto Bind",
            "0.2.0")]
        public override void EnsureAutoBind(GameObject go)
        {
            if (view != null)
            {
                return;
            }

            if (go == null)
            {
                Debug.LogError(
                    "[HomeView] Auto Bind failed: target GameObject is null.");
                return;
            }

            ComponentAutoBindTool autoBindTool =
                go.GetComponent<ComponentAutoBindTool>();
            if (autoBindTool == null)
            {
                Debug.LogError(
                    "[HomeView] Auto Bind failed: ComponentAutoBindTool was "
                    + "not found.",
                    go);
                return;
            }

            view = new UIView
            {
                statusText = autoBindTool.GetBindComponent<Text>(
                    0,
                    nameof(UIView.statusText)),
                showDetailButton = autoBindTool.GetBindComponent<Button>(
                    1,
                    nameof(UIView.showDetailButton)),
                queueDetailButton = autoBindTool.GetBindComponent<Button>(
                    2,
                    nameof(UIView.queueDetailButton)),
                replaceDetailButton = autoBindTool.GetBindComponent<Button>(
                    3,
                    nameof(UIView.replaceDetailButton)),
                closeButton = autoBindTool.GetBindComponent<Button>(
                    4,
                    nameof(UIView.closeButton))
            };
        }
    }
}
