using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using JasmineYamo.ComponentAutoBind;
using UnityEngine;
using BindData = JasmineYamo.ComponentAutoBind.ComponentAutoBindTool.BindData;

namespace JasmineYamo.ComponentAutoBind.Editor
{
    internal static class AutoBindCodeGenerator
    {
        public static string Generate(ComponentAutoBindTool target, AutoBindGlobalSetting setting)
        {
            if (target == null)
            {
                throw new ArgumentNullException(nameof(target));
            }

            if (setting == null)
            {
                throw new ArgumentNullException(nameof(setting));
            }

            string codePath = AutoBindPathUtility.GetResolvedCodePath(setting, target);
            if (string.IsNullOrWhiteSpace(codePath))
            {
                throw new InvalidOperationException("The Component Auto Bind code path is empty.");
            }

            string className = target.ClassName;
            if (!AutoBindFieldNameUtility.IsValidIdentifier(className))
            {
                throw new InvalidOperationException(
                    $"The generated class name '{className}' is not a valid C# identifier.");
            }

            if (!AutoBindFieldNameUtility.IsValidNamespace(target.Namespace ?? string.Empty))
            {
                throw new InvalidOperationException(
                    $"The generated namespace '{target.Namespace}' is not valid.");
            }

            Directory.CreateDirectory(codePath);
            string filePath = Path.Combine(codePath, $"{className}.BindComponents.cs");
            string generatedCode = BuildCode(target, className);
            File.WriteAllText(filePath, generatedCode, new UTF8Encoding(false));
            return filePath;
        }

        private static string BuildCode(ComponentAutoBindTool target, string className)
        {
            var bindComponents = new List<BindComponentInfo>();
            Type targetScriptType = target.m_targetScript == null
                ? null
                : target.m_targetScript.GetType();
            bool overridesEnsureAutoBind = HasOverridableEnsureAutoBindBase(targetScriptType);
            bool targetImplementsAutoBindTarget = targetScriptType != null
                && typeof(IAutoBindTarget).IsAssignableFrom(targetScriptType);

            List<BindData> bindDatas = target.BindDatas ?? new List<BindData>();
            for (int i = 0; i < bindDatas.Count; i++)
            {
                BindData data = bindDatas[i];
                if (data == null || data.BindCom == null)
                {
                    continue;
                }

                Type componentType = data.BindCom.GetType();
                bindComponents.Add(new BindComponentInfo(
                    GetTypeName(componentType),
                    AutoBindFieldNameUtility.BuildFieldName(data.Name),
                    i));
            }

            var builder = new StringBuilder(2048);
            builder.AppendLine("using System;");
            builder.AppendLine("using UnityEngine;");
            builder.Append("using ").Append(typeof(IAutoBindComponentSet).Namespace).AppendLine(";");
            builder.AppendLine();
            builder.AppendLine("// Generated by Component Auto Bind. Do not edit manually.");

            string namespaceName = target.Namespace ?? string.Empty;
            bool hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
            if (hasNamespace)
            {
                builder.Append("namespace ").Append(namespaceName).AppendLine();
                builder.AppendLine("{");
            }

            string classIndent = hasNamespace ? "\t" : string.Empty;
            string memberIndent = classIndent + "\t";
            string innerIndent = memberIndent + "\t";
            string methodInnerIndent = innerIndent + "\t";

            builder.Append(classIndent).Append("public partial class ").Append(className);
            if (!targetImplementsAutoBindTarget)
            {
                builder.Append(" : global::")
                    .Append(typeof(IAutoBindTarget).FullName);
            }

            builder.AppendLine();
            builder.Append(classIndent).AppendLine("{");
            builder.Append(memberIndent).AppendLine("[Serializable]");
            builder.Append(memberIndent).AppendLine(
                "public sealed class AutoBindComponentSet : global::"
                + typeof(IAutoBindComponentSet).FullName);
            builder.Append(memberIndent).AppendLine("{");

            for (int i = 0; i < bindComponents.Count; i++)
            {
                BindComponentInfo bindComponent = bindComponents[i];
                builder.Append(innerIndent)
                    .Append("public ")
                    .Append(bindComponent.TypeName)
                    .Append(' ')
                    .Append(bindComponent.FieldName)
                    .AppendLine(";");
            }

            builder.Append(memberIndent).AppendLine("}");
            builder.AppendLine();
            builder.Append(memberIndent)
                .AppendLine("private AutoBindComponentSet m_AutoBindComponents;");
            builder.AppendLine();
            builder.Append(memberIndent)
                .AppendLine(
                    "[global::System.CodeDom.Compiler.GeneratedCode(\"Component Auto Bind\", \"0.1.0\")]");
            builder.Append(memberIndent)
                .Append(overridesEnsureAutoBind
                    ? "public override void EnsureAutoBind(GameObject go)"
                    : "public void EnsureAutoBind(GameObject go)")
                .AppendLine();
            builder.Append(memberIndent).AppendLine("{");
            builder.Append(innerIndent).AppendLine("if (m_AutoBindComponents != null)");
            builder.Append(innerIndent).AppendLine("{");
            builder.Append(methodInnerIndent).AppendLine("return;");
            builder.Append(innerIndent).AppendLine("}");
            builder.AppendLine();
            builder.Append(innerIndent).AppendLine("if (go == null)");
            builder.Append(innerIndent).AppendLine("{");
            AppendLogStatement(
                builder,
                methodInnerIndent,
                className,
                "Auto Bind failed: target GameObject is null.",
                false);
            builder.Append(methodInnerIndent).AppendLine("return;");
            builder.Append(innerIndent).AppendLine("}");
            builder.AppendLine();
            builder.Append(innerIndent)
                .Append("global::")
                .Append(typeof(ComponentAutoBindTool).FullName)
                .Append(" autoBindTool = go.GetComponent<global::")
                .Append(typeof(ComponentAutoBindTool).FullName)
                .AppendLine(">();");
            builder.AppendLine();
            builder.Append(innerIndent).AppendLine("if (autoBindTool == null)");
            builder.Append(innerIndent).AppendLine("{");
            AppendLogStatement(
                builder,
                methodInnerIndent,
                className,
                "Auto Bind failed: ComponentAutoBindTool was not found.",
                true);
            builder.Append(methodInnerIndent).AppendLine("return;");
            builder.Append(innerIndent).AppendLine("}");
            builder.AppendLine();
            builder.Append(innerIndent).AppendLine("m_AutoBindComponents = new AutoBindComponentSet");
            builder.Append(innerIndent).AppendLine("{");

            for (int i = 0; i < bindComponents.Count; i++)
            {
                BindComponentInfo bindComponent = bindComponents[i];
                builder.Append(innerIndent)
                    .Append('\t')
                    .Append(bindComponent.FieldName)
                    .Append(" = autoBindTool.GetBindComponent<")
                    .Append(bindComponent.TypeName)
                    .Append(">(")
                    .Append(bindComponent.Index)
                    .Append(", nameof(AutoBindComponentSet.")
                    .Append(bindComponent.FieldName)
                    .AppendLine(")),");
            }

            builder.Append(innerIndent).AppendLine("};");
            builder.Append(memberIndent).AppendLine("}");
            builder.Append(classIndent).AppendLine("}");
            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString().Replace("\r\n", "\n");
        }

        private static void AppendLogStatement(
            StringBuilder builder,
            string indent,
            string className,
            string message,
            bool includeGameObject)
        {
            string escapedMessage = message.Replace("\\", "\\\\").Replace("\"", "\\\"");
            builder.Append(indent)
                .Append("Debug.LogError(\"")
                .Append('[')
                .Append(className)
                .Append("] ")
                .Append(escapedMessage)
                .Append("\"");
            if (includeGameObject)
            {
                builder.Append(", go");
            }

            builder.AppendLine(");");
        }

        private static string GetTypeName(Type componentType)
        {
            if (componentType == null)
            {
                throw new ArgumentNullException(nameof(componentType));
            }

            if (componentType.IsGenericType)
            {
                string genericName = componentType.GetGenericTypeDefinition().FullName;
                genericName = genericName.Substring(0, genericName.IndexOf('`'));
                Type[] genericArguments = componentType.GetGenericArguments();
                var builder = new StringBuilder("global::");
                builder.Append(genericName.Replace('+', '.'));
                builder.Append('<');
                for (int i = 0; i < genericArguments.Length; i++)
                {
                    if (i > 0)
                    {
                        builder.Append(", ");
                    }

                    builder.Append(GetTypeName(genericArguments[i]));
                }

                builder.Append('>');
                return builder.ToString();
            }

            string fullName = componentType.FullName ?? componentType.Name;
            return "global::" + fullName.Replace('+', '.');
        }

        private static bool HasOverridableEnsureAutoBindBase(Type targetScriptType)
        {
            for (Type currentType = targetScriptType?.BaseType;
                currentType != null && currentType != typeof(object);
                currentType = currentType.BaseType)
            {
                MethodInfo ensureMethod = currentType.GetMethod(
                    nameof(IAutoBindTarget.EnsureAutoBind),
                    BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly,
                    null,
                    new[] { typeof(GameObject) },
                    null);

                if (ensureMethod != null)
                {
                    return ensureMethod.IsPublic && ensureMethod.IsVirtual && !ensureMethod.IsFinal;
                }
            }

            return false;
        }

        private readonly struct BindComponentInfo
        {
            public BindComponentInfo(string typeName, string fieldName, int index)
            {
                TypeName = typeName;
                FieldName = fieldName;
                Index = index;
            }

            public string TypeName { get; }
            public string FieldName { get; }
            public int Index { get; }
        }
    }
}
