using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEngine;
using BindData = JasmineYamo.ComponentAutoBind.ComponentAutoBindTool.BindData;

namespace JasmineYamo.ComponentAutoBind.Editor
{
    internal static class AutoBindValidator
    {
        public static AutoBindValidationResult Validate(
            ComponentAutoBindTool target,
            AutoBindGlobalSetting setting)
        {
            var result = new AutoBindValidationResult();
            if (target == null)
            {
                result.AddError("The Component Auto Bind target is null.");
                return result;
            }

            ValidateTargetScript(target, result);
            ValidateCodePath(target, setting, result);
            ValidateBindDatas(target, result);
            return result;
        }

        private static void ValidateTargetScript(
            ComponentAutoBindTool target,
            AutoBindValidationResult result)
        {
            MonoBehaviour targetScript = target.m_targetScript;
            if (targetScript == null)
            {
                result.AddError("Assign a target MonoBehaviour to m_targetScript.");
                return;
            }

            if (targetScript.gameObject != target.gameObject)
            {
                result.AddError("The target MonoBehaviour must be attached to the Auto Bind root GameObject.");
            }

            Type targetType = targetScript.GetType();
            if (targetType.IsNested || targetType.IsGenericType)
            {
                result.AddError("The target MonoBehaviour must be a non-nested, non-generic type.");
            }

            MethodInfo declaredEnsureMethod = targetType.GetMethod(
                nameof(IAutoBindHost.EnsureAutoBind),
                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly,
                null,
                new[] { typeof(GameObject) },
                null);
            if (declaredEnsureMethod != null
                && !IsGeneratedEnsureAutoBindMethod(targetType, declaredEnsureMethod))
            {
                result.AddError(
                    "The target type must not already declare EnsureAutoBind(GameObject); "
                    + "that method is generated by Component Auto Bind.");
            }

            string configuredClassName = target.ClassName ?? string.Empty;
            string configuredNamespace = target.Namespace ?? string.Empty;
            string actualNamespace = targetType.Namespace ?? string.Empty;

            if (!AutoBindFieldNameUtility.IsValidIdentifier(configuredClassName)
                || !string.Equals(configuredClassName, targetType.Name, StringComparison.Ordinal))
            {
                result.AddError(
                    $"Generated class name '{configuredClassName}' must match target type '{targetType.Name}'.");
            }

            if (!AutoBindFieldNameUtility.IsValidNamespace(configuredNamespace)
                || !string.Equals(configuredNamespace, actualNamespace, StringComparison.Ordinal))
            {
                result.AddError(
                    $"Generated namespace '{configuredNamespace}' must match target namespace '{actualNamespace}'.");
            }
        }

        private static void ValidateCodePath(
            ComponentAutoBindTool target,
            AutoBindGlobalSetting setting,
            AutoBindValidationResult result)
        {
            if (setting == null)
            {
                result.AddError("Create the Component Auto Bind global settings asset first.");
                return;
            }

            string resolvedCodePath = AutoBindPathUtility.GetResolvedCodePath(setting, target);
            if (string.IsNullOrWhiteSpace(resolvedCodePath))
            {
                result.AddError("The generated code path is empty.");
                return;
            }

            if (!AutoBindPathUtility.IsPathUnderAssets(resolvedCodePath))
            {
                result.AddError(
                    $"The generated code path must be under the project Assets folder: {resolvedCodePath}");
                return;
            }

            if (!Directory.Exists(resolvedCodePath))
            {
                result.AddWarning(
                    $"The generated code folder does not exist yet and will be created: {resolvedCodePath}");
            }
        }

        private static void ValidateBindDatas(
            ComponentAutoBindTool target,
            AutoBindValidationResult result)
        {
            List<BindData> bindDatas = target.BindDatas;
            if (bindDatas == null || bindDatas.Count == 0)
            {
                result.AddWarning(
                    "There are no component bindings. The generated UIView will be empty.");
                return;
            }

            var generatedFieldNameToIndex = new Dictionary<string, int>(StringComparer.Ordinal);
            for (int i = 0; i < bindDatas.Count; i++)
            {
                BindData bindData = bindDatas[i];
                if (bindData == null)
                {
                    result.AddError($"Binding entry [{i}] is null.");
                    continue;
                }

                string bindName = bindData.Name;
                Component bindComponent = bindData.BindCom;
                string fieldName = AutoBindFieldNameUtility.BuildFieldName(bindName);

                if (string.IsNullOrWhiteSpace(bindName))
                {
                    result.AddError($"Binding entry [{i}] has an empty name.");
                }
                else if (!AutoBindFieldNameUtility.IsValidIdentifier(fieldName))
                {
                    result.AddError(
                        $"Binding entry [{i}] produces an invalid field name '{fieldName}' from '{bindName}'.");
                }
                else if (generatedFieldNameToIndex.TryGetValue(fieldName, out int duplicateIndex))
                {
                    result.AddError(
                        $"Binding entry [{i}] produces duplicate field '{fieldName}', already used by [{duplicateIndex}].");
                }
                else
                {
                    generatedFieldNameToIndex.Add(fieldName, i);
                }

                if (bindComponent == null)
                {
                    result.AddError($"Binding entry [{i}] has a missing component reference.");
                    continue;
                }

                if (!IsComponentUnderRoot(target.transform, bindComponent))
                {
                    result.AddError(
                        $"Binding entry [{i}] references component '{bindComponent.name}' outside the Auto Bind root.");
                }
            }
        }

        private static bool IsGeneratedEnsureAutoBindMethod(
            Type targetType,
            MethodInfo ensureMethod)
        {
            GeneratedCodeAttribute generatedCode =
                ensureMethod.GetCustomAttribute<GeneratedCodeAttribute>();
            if (generatedCode != null
                && string.Equals(
                    generatedCode.Tool,
                    "Component Auto Bind",
                    StringComparison.Ordinal))
            {
                return true;
            }

            if (HasGeneratedBindingShape(
                targetType,
                "UIView",
                "view",
                typeof(IUiViewComponent)))
            {
                return true;
            }

            return HasGeneratedBindingShape(
                targetType,
                "AutoBindComponentSet",
                "m_AutoBindComponents",
                null);
        }

        private static bool HasGeneratedBindingShape(
            Type targetType,
            string nestedTypeName,
            string fieldName,
            Type requiredContract)
        {
            Type bindingType = targetType.GetNestedType(
                nestedTypeName,
                BindingFlags.Public | BindingFlags.NonPublic);
            if (bindingType == null
                || (requiredContract != null
                    && !requiredContract.IsAssignableFrom(bindingType)))
            {
                return false;
            }

            FieldInfo bindingField = targetType.GetField(
                fieldName,
                BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly);
            return bindingField != null
                && bindingField.FieldType == bindingType;
        }

        private static bool IsComponentUnderRoot(Transform root, Component component)
        {
            return root != null
                && component != null
                && component.transform != null
                && (component.transform == root || component.transform.IsChildOf(root));
        }
    }
}
